### ISSUE TITLE
Azure pipeline not build master branch

### ISSUE THREAD

**Issue by gusmith** [data61/clkhash#266]
This is a misconfiguration of the the triggers in the azure pipeline file.
From Azure documentation:

> Includes are processed first, and then excludes are removed from that list.

So
```
trigger:
  branches: 
    include:
    - master
    eclude:
    - '*'
```
was setting the list to include to master, and then removing it.
